version: '3.8'

services:
  node:
    image: nexusolo/aws:lastest
    depends_on:
      - http
    networks:
      - reseau
    ports :
      - 3000:3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  http:
    image: nginx:1.25
    volumes:
      - ./http/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8082:80
    depends_on:
      - db
    networks:
      - reseau
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
    - ./db/db-init-scripts:/docker-entrypoint-initdb.d/
      # - ./data:/var/lib/postgresql/data
    networks:
      - reseau
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  reseau: