global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker-swarm'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_service_mode]
        regex: replicated
        action: keep
      - source_labels: [__meta_docker_service_label_com_prometheus_scrape]
        regex: true
        action: keep
      - source_labels: [__meta_docker_service_name]
        target_label: job
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']